CREATE TABLE IF NOT EXISTS users (
    id        SERIAL PRIMARY KEY,
  name      TEXT NOT NULL,
  email     TEXT NOT NULL UNIQUE,
  hashpass  TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE links ADD COLUMN user_id INTEGER REFERENCES users(id) ON DELETE CASCADE;